### ISSUE TITLE
Pop-up Windows Modal

### ISSUE THREAD

**Issue by mshorts** [mshorts/belvedere#26]
Make the log viewer & about windows modal (+AlwaysOnTop, -MinimizeBox; disable main GUI)

**Comment by mshorts** [comment]
change made in following commit:  http://github.com/mshorts/belvedere/commit/dc0f7dd4f9e044470d00b320bdfdf1d1f97e90d2

**Comment by DustinLuck** [comment]
Right now, the dialogs are not truly modal. To fully make a window modal, the following code should be implemented. This will disable the main window, causing the entire Belvedere program to only show up once in the taskbar and while Alt-Tabbing.

;when defining modal dialog
Gui,4: +owner +AlwaysOnTop -MinimizeBox +ToolWindow  ;suppresses taskbar button, always on top, removes minimize titlebar item

;directly before showing modal dialog
Gui 1:+Disabled ;disable the main GUI

;when dismissing the modal dialog
Gui 1:-Disabled ;re-enable the main GUI

Also, adding Gui 1:+OwnDialogs to the main window will cause all message boxes and file/folder selection dialogs to be modal and owned by the main window.

**Comment by mshorts** [comment]
more changes in this commit:  08dc2b79f42b1d6f4bfa2fc4d143c361d76a3b85

still some more work to be done

**Comment by mshorts** [comment]
finished up modal work; closed by 064c1f4137bfe839ce738bb5c4fb3539db2fbd3e
