### ISSUE TITLE
Exclude files with certain attributes

### ISSUE THREAD

**Issue by mshorts** [mshorts/belvedere#37]
Add the ability to exclude files with certain attributes when processing a rule.

**Comment by mshorts** [comment]
added ability to turn off exit confirmation
added ability to exclude files based on attributes; this closed by 8494c1b4c56769d3b5424b36f0821d797d302f54
fixed display bug with custom action button

**Comment by InfiniteMonkeys** [comment]
I see this issue is closed, but wondered whether the Archive attribute could be added.  Unlike H,S,R, it can be set arbitrarily without altering the way a file can be viewed or manipulated.

**Comment by mshorts** [comment]
please add this as a new issue and we'll include it as an enhancement for the next version
