### ISSUE TITLE
Launch program

### ISSUE THREAD

**Issue by jackelmatador** [mshorts/belvedere#39]
I added this to belvedere a long time ago, but unfortunately lost the source in a crash before I made a submission.  Basically it was just an extra drop down than was a run command.  So if anything happened to the folder you could run a command line program.  This would be very useful if say I want to automatically convert a TV show I just recorded.  I could first copy it to a new folder then run handbrake for example.

**Comment by mshorts** [comment]
does #7 take care of what you're looking todo?  Essentially you put what command (and any parameters) that you want run, and it will add the filename that was matched as the final parameter

**Comment by jackelmatador** [comment]
Thanks for the heads up I did a build with autohotkey and it works like a charm!
