### ISSUE TITLE
Add to iTunes Action

### ISSUE THREAD

**Issue by mshorts** [mshorts/belvedere#44]
Create the Add to iTunes Action

**Comment by HyShai** [comment]
I just use the move rule to Automatically Add to iTunes folder

**Comment by mshorts** [comment]
Yep, that didn't exist when this was first proposed for Belvedere.  I supposed we could probably remove it at this point unless people are looking to do something a little more complex than moving it to the Add to iTunes folder.

**Comment by tylermumford** [comment]
It's true that it's as easy as moving the file to that folder, but it would be convenient ('specially for people who don't know about that folder) if it were a predefined action in Belvedere.

**Comment by mshorts** [comment]
Good point.  Then we'll look at including this in the next release!
