### ISSUE TITLE
Foreign Language filename not moved

### ISSUE THREAD

**Issue by HyShai** [mshorts/belvedere#47]
A file with a foreign language filename does not get moved with the 'move' rule (maybe other rules too-didn't test) until filename is manually changed.

**Comment by mshorts** [comment]
Can you provide an example?

**Comment by HyShai** [comment]
יומי_לעווי_מגיש_יש_אהבת_השם_בישראל_חסידיניוז_08_Pen_Pen_Ten_Ten.mp3 A filename like this is not moved

**Comment by mshorts** [comment]
Right now Belvedere doesn't support Unicode file names, we can look at adding this in the future possibly.

**Comment by wrygiel** [comment]
Hi there!

> we can look at adding this in the future possibly

Just wondering - why is this issue marked as closed then? :)
